export const types = {
  SEND_REQUEST_GET_PRODUCT_API_REQUEST: 'SEND_REQUEST_GET_PRODUCT_API_REQUEST',
  SEND_REQUEST_GET_PRODUCT_API_SUCCESS: 'SEND_REQUEST_GET_PRODUCT_API_SUCCESS',
  SEND_REQUEST_GET_PRODUCT_API_FAILURE: 'SEND_REQUEST_GET_PRODUCT_API_FAILURE',
  SEND_REQUEST_GET_PRODUCT_API_LIST_END:
    'SEND_REQUEST_GET_PRODUCT_API_LIST_END',
};
